<a href="https://colab.research.google.com/github/MahaleVivek/pytorch_a_deep_learning_journey/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
## pytorch fundamentals

In [17]:
import torch
print(torch.__version__)

2.2.1+cu121


In [18]:
!nvidia-smi

Mon May 20 06:20:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0              34W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [19]:
## Intro to tensors

# create tensors
#Pytorch tensors are created using torch.tensor

In [20]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [21]:
scalar.ndim

0

In [22]:
# get tensor back as python int
scalar.item()

7

In [23]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [24]:
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [26]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [27]:
matrix.ndim

2

In [28]:
matrix[0]

tensor([7, 8])

In [29]:
matrix[1]

tensor([ 9, 10])

In [30]:
matrix.shape

torch.Size([2, 2])

In [31]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [35]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2135, 0.1338, 0.4649, 0.9588],
        [0.8939, 0.7270, 0.9963, 0.9187],
        [0.6410, 0.0036, 0.4408, 0.5290]])

In [36]:
random_tensor.ndim

2

In [37]:
3 #create a random tensor with similar shaoe of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channels (Red, Green, Blue)
random_image_size_tensor

tensor([[[0.6336, 0.3623, 0.8456],
         [0.5171, 0.5863, 0.1297],
         [0.8819, 0.5433, 0.7582],
         ...,
         [0.2470, 0.5686, 0.1733],
         [0.2169, 0.0456, 0.4448],
         [0.6673, 0.8779, 0.9085]],

        [[0.6379, 0.8863, 0.1068],
         [0.0711, 0.4590, 0.6458],
         [0.6176, 0.2723, 0.4283],
         ...,
         [0.9383, 0.2242, 0.5541],
         [0.1190, 0.3586, 0.4741],
         [0.0574, 0.4060, 0.1422]],

        [[0.5721, 0.2733, 0.6830],
         [0.7485, 0.6800, 0.2129],
         [0.2198, 0.0168, 0.2336],
         ...,
         [0.2637, 0.2095, 0.5997],
         [0.3845, 0.2447, 0.2169],
         [0.9328, 0.2342, 0.8825]],

        ...,

        [[0.2072, 0.7651, 0.5480],
         [0.0225, 0.0773, 0.5401],
         [0.1492, 0.3036, 0.4760],
         ...,
         [0.5381, 0.2330, 0.1465],
         [0.0394, 0.3560, 0.1814],
         [0.6084, 0.7814, 0.7719]],

        [[0.7645, 0.5794, 0.9202],
         [0.4807, 0.5775, 0.2581],
         [0.

In [38]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [39]:
random_tensor_1 = torch.rand(1, 5, 5)
random_tensor_1

tensor([[[0.2359, 0.5737, 0.7364, 0.6559, 0.3248],
         [0.1883, 0.5408, 0.9621, 0.9064, 0.6677],
         [0.8907, 0.9986, 0.0401, 0.9648, 0.5964],
         [0.8687, 0.0598, 0.8133, 0.8406, 0.4475],
         [0.6913, 0.9722, 0.2472, 0.3626, 0.7796]]])

In [40]:
random_tensor_1.shape, random_tensor_1.ndim

(torch.Size([1, 5, 5]), 3)

### Zeros and ones

In [41]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [44]:
random_tensor.dtype

torch.float32

### create a range of tensors and tensors-like

In [45]:
#use torch.range
torch.range(0, 10)

<ipython-input-45-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
step_one_to_thousand = torch.arange(start=1, end=1000, step=99)
step_one_to_thousand

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [49]:
# create tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [50]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [51]:
float_32_tensor.dtype

torch.float32

In [52]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Tensor datatypes

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [53]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # what datatype is the tensor
                            device=None, # what device is your tensor on
                            requires_grad=False) # whether or not to track gradients with tensors operations
float_tensor

tensor([3., 6., 9.])

In [54]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [55]:
mul_tensor = float_16_tensor * float_32_tensor
mul_tensor

tensor([ 9., 36., 81.])

In [56]:
mul_tensor.dtype

torch.float32

In [57]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [58]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use`tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [59]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6310, 0.7589, 0.3634, 0.7194],
        [0.3826, 0.3499, 0.4632, 0.2606],
        [0.1445, 0.8327, 0.5520, 0.0500]])

In [60]:
# find out details about tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"\nShape of tensor: {some_tensor.shape}")
print(f"\nDevice of tensor on: {some_tensor.device}")

tensor([[0.6310, 0.7589, 0.3634, 0.7194],
        [0.3826, 0.3499, 0.4632, 0.2606],
        [0.1445, 0.8327, 0.5520, 0.0500]])
Datatype of tensor: torch.float32

Shape of tensor: torch.Size([3, 4])

Device of tensor on: cpu


## Manipulating tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [61]:
# create a tensor and Addition

tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [62]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [63]:
tensor

tensor([1, 2, 3])

In [64]:
tensor - 10

tensor([-9, -8, -7])

In [65]:
# Try out PyTorch Inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication

visit mathisfun.com page

Two main ways of the performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **ineer dimansions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [66]:
## Matrix multiplication - Element wise
tensor

tensor([1, 2, 3])

In [67]:
print(tensor, " * ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [68]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 2.26 ms, sys: 14 µs, total: 2.27 ms
Wall time: 6.3 ms


tensor(14)

In [69]:
%%time
1 * 1 + 2 * 2 + 3 * 3   # matrix multiplication by hand

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs


14

In [70]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.59 ms, sys: 41 µs, total: 4.63 ms
Wall time: 6.65 ms


In [71]:
## one of the most of the common errors in deep learning: shape learning

# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)    # torch.mm is same as torch.matmul (alias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues we can manipulate the shape of one of our ensors using transpose

A **transpose** switched the axes or dimensions of a given tensor

In [73]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [74]:
tensor_B.T    # T is for transpose

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [75]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [76]:
#The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("\nOutput:")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape = {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape = torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [77]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [78]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [79]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [80]:
# find mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
## Find the mean: note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

In [ ]:
x.type(torch.float32).mean()

In [ ]:
## find sum
torch.sum(x), x.sum()

In [ ]:
## finding the positional min and max of tensors

In [ ]:
x = torch.arange(1, 100, 10)
x

In [81]:
#find the position in the tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [82]:
x[0]

tensor(0)

In [83]:
# find the position in tensor that has the maximum vakue with argmax()
x.argmax()

tensor(9)

In [84]:
x[9]

tensor(90)

In [85]:
x[-1]

tensor(90)

### Reshaping, viewing, squeezing, unsqeezing and stacking

* Reshaping - reshapes an input tensor to defined shape
* View - return a view of input tensor of certain shape but keep the same memory as original tensor
* Stacking - combines multiple tensors on top of each other (vstack) and side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Usqueeze - add a `1` dimension to a greae tensor
* Permute - Return a view of the iput with the dimensions permuted (swapped) in a certain way

In [86]:
# let's create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
# add an extra dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# add an extra dimensions
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [89]:
y = torch.arange(1., 11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [90]:
# add an extra dimensions
y_reshaped = y.reshape(5, 2)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [91]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# changing z chnages z (because a view of a tensor shares tha same memory as the origin)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [93]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [94]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [95]:
# torch.sqeeze() - removes all single dimensions from target input tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimenions from x_reshaped
x_sqeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_sqeezed}")
print(f"New shape: {x_sqeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [96]:
x_reshaped.shape

torch.Size([9, 1])

In [97]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
x_reshaped.squeeze().shape

torch.Size([9])

In [99]:
# torch.unsqueezed() - adds a single dimensions to a target tensor at a specific dimension
print(f"Previous target: {x_sqeezed}")
print(f"Previous shape: {x_sqeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_sqeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [100]:
# torch.permute - rearranges the dimensions of a target tensor in specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
#print(f"X original tensor: {x_original}")

3 #permute the original tensor to rearrange the ais (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"X original shape: {x_original.shape}")
print(f"X permute shape: {x_permuted.shape}")

X original shape: torch.Size([224, 224, 3])
X permute shape: torch.Size([3, 224, 224])


### Selecting data (Indexing)

Indexing with PyTorch is similar to indexing in NumPy

In [101]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [102]:
# let's index on our new index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
# let's index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [104]:
x[0, 0]

tensor([1, 2, 3])

In [105]:
# let's index on the most ineer bracket
x[0][0][0]

tensor(1)

In [106]:
x[0][1][1]

tensor(5)

In [107]:
x[0][2][2]

tensor(9)

In [108]:
# get all the values of 0th and 1st dimensions but only index 1 of 2nd dimenions
x[:, :, 1]

tensor([[2, 5, 8]])

In [109]:
# get all values of 0th dimensions but only the 1 index value and 2nd dimension
x[:, 1, 1]

tensor([5])

In [110]:
#get index 0 of 0th and 1st dimensions and all values of 2nd dimensions
x[0, 0, :]

tensor([1, 2, 3])

In [111]:
# index on x to return 9
x[0][2][2]

tensor(9)

In [112]:
# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

Numpy is a popular scientific python numericl computing library

and because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.NumPy()`

In [113]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #WARNING: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
array.dtype

dtype('float64')

In [115]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [116]:
#Change the value of an array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [117]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [118]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representaions of the data -> again -> again -> again...`


To reduce randomness in neural networks and pythorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [119]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Random tensor A: \n{random_tensor_A}")
print(f"\nRandom tensor B: \n{random_tensor_B}")
print("\n",random_tensor_A == random_tensor_B)

Random tensor A: 
tensor([[0.1327, 0.6106, 0.6565, 0.6043],
        [0.3491, 0.6399, 0.6393, 0.8306],
        [0.8764, 0.2845, 0.2219, 0.6851]])

Random tensor B: 
tensor([[0.9207, 0.2388, 0.6807, 0.1695],
        [0.7500, 0.8772, 0.3509, 0.1056],
        [0.2704, 0.7059, 0.6066, 0.6463]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Random tensor C: \n{random_tensor_C}")
print(f"Random tensor D: \n{random_tensor_D}")
print(random_tensor_C == random_tensor_D)

Random tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = Faster computations on numbers, thanks to cuda + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU
1. Easiest - Use google colab for a free GPU (options to upgrade as well)
2. Use your own GPUs - takes a little bit of setup and reqires the investment of purchsing
3. Use cloud computing


For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setup, to do this, refer PyTorch documentaions: https://pytorch.org/get-started/locally/

In [121]:
## check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Eg. run on GPU if available, else default to CPU

In [122]:
## Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [123]:
# count number of devices
torch.cuda.device_count()

1

In [124]:
## putting tensors (and models) on the GPU
#The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [125]:
# create a tensor (default on the CPU)
import torch
tensor = torch.tensor([1, 2, 3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [126]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [127]:
### 4. moving tensors back to CPU

In [128]:
# if tensor is on the GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [129]:
# to fix the GPU tensor to NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])