<a href="https://colab.research.google.com/github/MahaleVivek/pytorch_a_deep_learning_journey/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## pytorch fundamentals

In [ ]:
import torch
print(torch.__version__)

2.2.1+cu121


In [ ]:
!nvidia-smi

Sun Apr 28 12:18:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
## Intro to tensors

# create tensors
#Pytorch tensors are created using torch.tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1687, 0.4080, 0.4523, 0.9175],
        [0.2754, 0.9706, 0.0356, 0.6557],
        [0.0515, 0.8189, 0.2741, 0.6477]])

In [ ]:
random_tensor.ndim

2

In [ ]:
3 #create a random tensor with similar shaoe of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channels (Red, Green, Blue)
random_image_size_tensor

tensor([[[0.1921, 0.7290, 0.4104],
         [0.8436, 0.0114, 0.4962],
         [0.5719, 0.3987, 0.0392],
         ...,
         [0.6190, 0.4244, 0.7401],
         [0.0106, 0.5568, 0.0551],
         [0.0176, 0.4217, 0.3511]],

        [[0.2230, 0.8697, 0.0294],
         [0.5561, 0.3587, 0.4258],
         [0.9326, 0.0237, 0.8188],
         ...,
         [0.9398, 0.9781, 0.0043],
         [0.1682, 0.2009, 0.2956],
         [0.9962, 0.4789, 0.6230]],

        [[0.8478, 0.7939, 0.9241],
         [0.3358, 0.1015, 0.0828],
         [0.0266, 0.5862, 0.7315],
         ...,
         [0.7251, 0.2177, 0.0945],
         [0.8289, 0.5862, 0.8655],
         [0.8156, 0.9399, 0.3662]],

        ...,

        [[0.8398, 0.8716, 0.6738],
         [0.0675, 0.7426, 0.4177],
         [0.0349, 0.5684, 0.2729],
         ...,
         [0.2623, 0.6624, 0.8960],
         [0.7676, 0.0022, 0.7906],
         [0.7049, 0.5261, 0.5708]],

        [[0.2856, 0.1154, 0.5158],
         [0.9640, 0.2931, 0.3729],
         [0.

In [ ]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
random_tensor_1 = torch.rand(1, 5, 5)
random_tensor_1

tensor([[[0.1711, 0.7390, 0.2879, 0.6979, 0.8281],
         [0.9305, 0.0060, 0.5522, 0.1309, 0.7034],
         [0.5861, 0.8177, 0.9727, 0.5066, 0.7920],
         [0.5951, 0.4734, 0.9919, 0.7932, 0.6598],
         [0.2743, 0.3896, 0.0483, 0.5017, 0.6369]]])

In [ ]:
random_tensor_1.shape, random_tensor_1.ndim

(torch.Size([1, 5, 5]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### create a range of tensors and tensors-like

In [ ]:
#use torch.range
torch.range(0, 10)

<ipython-input-42-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step_one_to_thousand = torch.arange(start=1, end=1000, step=99)
step_one_to_thousand

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [ ]:
# create tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_tensor

tensor([3., 6., 9.], dtype=torch.float16)