<a href="https://colab.research.google.com/github/MahaleVivek/pytorch_a_deep_learning_journey/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## pytorch fundamentals

In [2]:
import torch
print(torch.__version__)

2.2.1+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
## Intro to tensors

# create tensors
#Pytorch tensors are created using torch.tensor

In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
#create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5634, 0.5690, 0.8931, 0.6776],
        [0.1926, 0.1445, 0.0715, 0.3077],
        [0.4842, 0.1359, 0.7181, 0.6079]])

In [21]:
random_tensor.ndim

2

In [22]:
3 #create a random tensor with similar shaoe of an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channels (Red, Green, Blue)
random_image_size_tensor

tensor([[[0.3393, 0.9932, 0.9752],
         [0.7535, 0.7207, 0.7899],
         [0.1817, 0.7906, 0.7617],
         ...,
         [0.9071, 0.6592, 0.0529],
         [0.7971, 0.7693, 0.7847],
         [0.8914, 0.3113, 0.3561]],

        [[0.5299, 0.9741, 0.9950],
         [0.8730, 0.7796, 0.8684],
         [0.8463, 0.0335, 0.6422],
         ...,
         [0.2329, 0.0730, 0.2880],
         [0.8910, 0.2097, 0.3816],
         [0.5496, 0.1131, 0.4596]],

        [[0.4556, 0.6163, 0.2937],
         [0.9329, 0.4302, 0.8142],
         [0.4125, 0.7585, 0.9675],
         ...,
         [0.1672, 0.3408, 0.0464],
         [0.7486, 0.9628, 0.5990],
         [0.0174, 0.0446, 0.2506]],

        ...,

        [[0.3695, 0.0352, 0.0492],
         [0.4238, 0.8583, 0.2289],
         [0.9833, 0.2095, 0.8671],
         ...,
         [0.9631, 0.6688, 0.8732],
         [0.3927, 0.9585, 0.6334],
         [0.1093, 0.7092, 0.7493]],

        [[0.1438, 0.8399, 0.7856],
         [0.7619, 0.7294, 0.7884],
         [0.

In [23]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [24]:
random_tensor_1 = torch.rand(1, 5, 5)
random_tensor_1

tensor([[[0.3134, 0.5583, 0.8107, 0.8002, 0.0841],
         [0.8338, 0.5834, 0.7957, 0.8968, 0.0040],
         [0.2406, 0.9112, 0.5189, 0.5793, 0.8270],
         [0.1775, 0.9673, 0.4516, 0.1184, 0.9426],
         [0.9224, 0.5494, 0.3675, 0.3424, 0.0519]]])

In [25]:
random_tensor_1.shape, random_tensor_1.ndim

(torch.Size([1, 5, 5]), 3)

### Zeros and ones

In [26]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

### create a range of tensors and tensors-like

In [30]:
#use torch.range
torch.range(0, 10)

<ipython-input-30-a089c3bf7207>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
step_one_to_thousand = torch.arange(start=1, end=1000, step=99)
step_one_to_thousand

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [34]:
# create tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [35]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Tensor datatypes

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [38]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # what datatype is the tensor
                            device=None, # what device is your tensor on
                            requires_grad=False) # whether or not to track gradients with tensors operations
float_tensor

tensor([3., 6., 9.])

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
mul_tensor = float_16_tensor * float_32_tensor
mul_tensor

tensor([ 9., 36., 81.])

In [41]:
mul_tensor.dtype

torch.float32

In [42]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor Attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use`tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [44]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6875, 0.6132, 0.6019, 0.1286],
        [0.0541, 0.0589, 0.9821, 0.1263],
        [0.7287, 0.6355, 0.8686, 0.8994]])

In [45]:
# find out details about tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"\nShape of tensor: {some_tensor.shape}")
print(f"\nDevice of tensor on: {some_tensor.device}")

tensor([[0.6875, 0.6132, 0.6019, 0.1286],
        [0.0541, 0.0589, 0.9821, 0.1263],
        [0.7287, 0.6355, 0.8686, 0.8994]])
Datatype of tensor: torch.float32

Shape of tensor: torch.Size([3, 4])

Device of tensor on: cpu


## Manipulating tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [46]:
# create a tensor and Addition

tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [47]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [48]:
tensor

tensor([1, 2, 3])

In [49]:
tensor - 10

tensor([-9, -8, -7])

In [50]:
# Try out PyTorch Inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication

visit mathisfun.com page

Two main ways of the performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **ineer dimansions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [51]:
## Matrix multiplication - Element wise
tensor

tensor([1, 2, 3])

In [52]:
print(tensor, " * ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 740 µs, sys: 951 µs, total: 1.69 ms
Wall time: 8.15 ms


tensor(14)

In [54]:
%%time
1 * 1 + 2 * 2 + 3 * 3   # matrix multiplication by hand

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


14

In [55]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.63 ms, sys: 932 µs, total: 2.56 ms
Wall time: 6.53 ms


In [59]:
## one of the most of the common errors in deep learning: shape learning

# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)    # torch.mm is same as torch.matmul (alias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [60]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues we can manipulate the shape of one of our ensors using transpose

A **transpose** switched the axes or dimensions of a given tensor

In [64]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [63]:
tensor_B.T    # T is for transpose

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [65]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [68]:
#The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("\nOutput:")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape = {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape = torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [73]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [70]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [71]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [76]:
# find mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [77]:
## Find the mean: note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [78]:
x.type(torch.float32).mean()

tensor(45.)

In [80]:
## find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
## finding the positional min and max of tensors